apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-and-expose
spec:
  params:
    - name: APP_NAME
      type: string
    - description: The namespace where the application will be deployed
      name: NAMESPACE
      type: string
  steps:
    - name: deploy
      args:
        - new-app
        - $(params.APP_NAME)
        - '--name=$(params.APP_NAME)'
        - '--namespace=$(params.NAMESPACE)'
      command:
        - oc
      image: openshift/origin-cli
      resources: {}
    - name: patch-port
      args:
        - patch
        - service
        - test
        - '--patch'
        - |
          {
            "spec": {
              "ports": [
                {
                  "name": "$(params.APP_NAME)",
                  "port": 8080,
                  "targetPort": 3000
                }
              ]
            }
          }
      ## the default port created by s2i is 8080, while react runs on port 3000
      command:
        - oc
      image: openshift/origin-cli
      resources: {}
    - name: expose
      args:
        - create
        - route
        - edge
        - $(params.APP_NAME)
        - '--service=$(params.APP_NAME)'
        - '--port=3000'
      command:
        - oc
      image: openshift/origin-cli
      resources: {}