apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: react-deploy
spec:
  params:
    - name: APP_NAME
      type: string
    - name: IMAGE_TAG
      type: string
  steps:
    - args:
        - >
          # Load the image from the shared workspace

          oc import-image
          $(workspaces.shared-data.path)/$(params.APP_NAME)-$(params.IMAGE_TAG).tar
          --confirm

          # Deploy the application using the imported image

          oc new-app $(params.APP_NAME):$(params.IMAGE_TAG)
          --name=$(params.APP_NAME)

          oc expose svc/$(params.APP_NAME)
      command:
        - /bin/sh
        - '-c'
      image: 'quay.io/openshift/origin-cli:latest'
      name: deploy
      resources: {}
