apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: react-workspace
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Build Tools
    tekton.dev/tags: build-tool
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le"
spec:
  params:
    - description: 'path to context, to be moved to the root directory'
      name: CONTEXT_DIR
      type: string
  steps:
    - args:
        - |
          cp -r /workspace/source/$(params.CONTEXT_DIR)/* /workspace/source
      command:
        - sh
        - '-c'
      image: registry.redhat.io/ubi8/ubi-minimal:latest
      name: adjust-workspace
      resources: {}
  workspaces:
    - description: workspace of clone repo
      name: source
