apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: react-build-trigger
spec:
  params:
  - name: appName
    default: simple-react
  - name: repoUrl
    default: https://github.com/bcgov/pipeline-templates.git
  - name: branchName
    default: main
  - name: pathToContext
    default: ./tekton/demo/simple-react
  - name: imageTag
    default: v1
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: react-build-run-
    spec:
      pipelineRef:
        name: p-react-build
      params:
      - name: appName
        value: $(tt.params.appName)
      - name: repoUrl
        value: $(tt.params.repoUrl)
      - name: branchName
        value: $(tt.params.branchName)
      - name: pathToContext
        value: $(tt.params.pathToContext)
      - name: imageTag
        value: $(tt.params.imageTag)
      workspaces:
      - name: shared-data
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 100Mi
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: react-build-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github-listener
      interceptors:
        - github:
            secretRef:
              secretName: github-webhook-secret
              secretKey: secretToken
            eventTypes:
              - pull_request
              - push
      bindings:
        - ref: react-build-trigger-binding
      template:
        ref: react-build-trigger
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: react-build-trigger-binding
spec:
  params:
  - name: branchName
    value: $(body.ref)
  - name: repoUrl
    value: $(body.repository.url)
  - name: contenttype
    value: $(header.Content-Type)
  - name: imageTag
    value: $(body.head_commit.message)
