apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: react-build
spec:
  params:
    - name: appName
      type: string
      description: Name of App that will be deployed.
    - name: repoUrl
      type: string
      description: The git repository URL to clone from.
    - name: branchName
      type: string
      description: The git branch to clone.
    - name: pathToContext
      type: string
    - name: namespace
      type: string
  workspaces:
    - name: shared-data
      description: |
        This workspace will receive the cloned git repo and be passed
        to the next Task for the repo's README.md file to be read.
  tasks:
    - name: fetch-repo
      taskRef:
        name: t-git-clone
      params:
        - name: url
          value: $(params.repoUrl)
        - name: revision
          value: $(params.branchName)
      workspaces:
        - name: output
          workspace: shared-data

    - name: react-build
      taskRef:
        name: t-react-build
      runAfter: 
        - fetch-repo
      params: 
        - name: CONTEXT_DIR
          value: "$(params.pathToContext)"
        - name: OUTPUT_DIR
          value: image-registry.openshift-image-registry.svc:5000/$(params.namespace)/simple-react:latest
      workspaces:
        - name: source
          workspace: shared-data

    # - name: react-deploy
    #   taskRef:
    #     name: t-react-deploy
    #   runAfter: 
    #     - react-build
    #   params:
    #     - name: APP_NAME
    #       value: $(params.appName)
        # - name: command
        #   value: create
        # - name: arguments
        #   value:
        #     - "deploymentconfig"
        #     - $(params.appName)
        #     - "--image=$(params.appName):latest"

    