apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: trivy
spec:
  workspaces:
    - name: shared-data
      description: |
        This workspace will receive the cloned git repo and be passed
        to the next Task for the repo's README.md file to be read.
    - name: ssh-creds
      description: |
        This workspace will provide ssh credentials to the git-clone task.
    - name: docker-config
      description: |
        This workspace will provide docker credentials to the docker-build-push task.
  params:
  - name: repoUrl
    type: string
  - name: branchName
    type: string
  - name: targetImage
    type: string
  tasks:
    - name: fetch-repository
      taskRef:
        name: t-git-clone
      workspaces:
        - name: output
          workspace: shared-data
        - name: ssh-directory
          workspace: ssh-creds
      params:
        - name: url
          value: $(params.repoUrl)
        - name: deleteExisting
          value: "true"
        - name: revision
          value: $(params.branchName)
    - name: trivy-scan
      taskRef:
        name: t-trivy-scanner
      runAfter:
        - fetch-repository
      params:
        - name: TARGET_IMAGE
          value: $(params.targetImage)
      workspaces:
        - name: source
          workspace: shared-data
