name: owasp-scan
env:
  ## OWASP ZAP PARAMS
  ZAP_SCAN_TYPE: 'base' # Accepted values are base and full.
  ZAP_TARGET_URL: http://www.itsecgames.com
  ZAP_DURATION: '2'
  ZAP_MAX_DURATION: '5'

  # PUBLISH RESULTS TO WEBPAGE
  ## Creates a pre-signed URL with the results...
  ZAP_GCP_PUBLISH: 'true'
  ZAP_GCP_PROJECT: phronesis-310405
  ZAP_GCP_BUCKET: 'zap-scan-results'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'
jobs:
  zap_base:
    runs-on: ubuntu-latest
    name: OWASP ZAP Scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        if: ${{ env.ZAP_GCP_PUBLISH == 'true' }}
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.ZAP_GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: ZAP Base Scan
        if: ${{ env.ZAP_SCAN_TYPE == 'base' }}
        uses: zaproxy/action-baseline@v0.6.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: ${{ env.ZAP_TARGET_URL }}
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -d -T ${{ env.ZAP_MAX_DURATION }} -m ${{ env.ZAP_DURATION }}'
          issue_title: OWAP Baseline
      - name: ZAP Full Scan
        if: ${{ env.ZAP_SCAN_TYPE == 'full' }}
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: ${{ env.ZAP_TARGET_URL }}
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -d -T ${{ env.ZAP_MAX_DURATION }} -m ${{ env.ZAP_DURATION }}'
      - name: Create Artifact Directory
        if: ${{ env.ZAP_GCP_PUBLISH == 'true' }}
        run: |
          mkdir -p public/zap
      - name: Publish Reports to Github
        uses: actions/download-artifact@v2
        with:
          name: zap_scan
          path: public/zap
      - name: Rename Markdown
        if: ${{ env.ZAP_GCP_PUBLISH == 'true' }}
        run: |
          mv public/zap/report_md.md public/zap/README.md
      - name: ZAP Results
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          branch: zap-scan
          folder: public/zap
      - name: GCP Publish Results URL
        if: ${{ env.ZAP_GCP_PUBLISH == 'true' }}
        run: |
          echo "$GCP_SA_KEY" > gcp-sa-key.json
          gsutil mb gs://${{ env.ZAP_GCP_BUCKET }} || echo "Bucket already exists..."
          gsutil cp public/zap/report_html.html gs://${{ env.ZAP_GCP_BUCKET }}
          echo "URL expires in 10 minutes..."
          gsutil signurl -d 10m gcp-sa-key.json gs://${{ env.ZAP_GCP_BUCKET }}/report_html.html
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
